version: '3'
services:
  git:
    image: gitlab/gitlab-ce
    volumes:
    - ./data:/var/opt/gitlab
    - ./logs:/var/log/gitlab
    - ./conf:/etc/gitlab
    ports:
    - "80:80"
    - "22:22"
    - "443:443"
