version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis
    volumes: 
    - ./redis.conf:/data/redis.conf
    ports:
    - "6379:6379"
    command: redis-server /data/redis.conf